---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/blog
  label: Blog
  create: all
  match: "**/*.md"
upload_dir: src/img/christine
public_path: "/src/img/christine"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "/build"
  install_dependencies_command: npm install
  preview_docker_image: node:8.17.0
  mount_path: build
  working_dir: "/srv"
  instant_preview_command: gulp
